# Generated by Django 6.0.3 on 2026-04-17 10:42

import common.models.base_model
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

  initial = True

  dependencies = [
    ('contenttypes', '0002_remove_content_type_name'),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name='Notification',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('message', models.TextField(verbose_name='메시지')),
        (
          'category',
          models.CharField(
            choices=[('interview', '면접'), ('resume', '이력서'), ('jd', '채용공고'), ('system', '시스템')],
            db_index=True,
            max_length=20,
            verbose_name='카테고리'
          )
        ),
        ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='읽음 여부')),
        ('notifiable_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='관련 객체 PK')),
        (
          'notifiable_type',
          models.ForeignKey(
            blank=True,
            null=True,
            on_delete=django.db.models.deletion.SET_NULL,
            to='contenttypes.contenttype',
            verbose_name='관련 모델 타입'
          )
        ),
        (
          'user',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='notifications',
            to=settings.AUTH_USER_MODEL,
            verbose_name='사용자'
          )
        ),
      ],
      options={
        'verbose_name': '알림',
        'verbose_name_plural': '알림 목록',
        'db_table': 'notifications',
        'ordering': ['-created_at'],
        'get_latest_by': 'created_at',
        'abstract': False,
        'indexes': [
          models.Index(fields=['-created_at'], name='notificatio_created_8fa075_idx'),
          models.Index(fields=['-updated_at'], name='notificatio_updated_6ca2f2_idx'),
          models.Index(fields=['user', '-created_at'], name='notif_user_created_idx')
        ],
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
  ]
