# Generated by Django 6.0.3 on 2026-04-29 14:12

import common.models.base_model
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('notifications', '0001_initial'),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name='UserEmailNotificationSettings',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('streak_reminder_opted_in_at', models.DateTimeField(blank=True, null=True, verbose_name='스트릭 리마인더 동의 시각')),
        ('streak_reminder_opted_out_at', models.DateTimeField(blank=True, null=True, verbose_name='스트릭 리마인더 거절 시각')),
        ('streak_expire_opted_in_at', models.DateTimeField(blank=True, null=True, verbose_name='스트릭 만료 경고 동의 시각')),
        ('streak_expire_opted_out_at', models.DateTimeField(blank=True, null=True, verbose_name='스트릭 만료 경고 거절 시각')),
        ('report_ready_opted_in_at', models.DateTimeField(blank=True, null=True, verbose_name='면접 리포트 완성 동의 시각')),
        ('report_ready_opted_out_at', models.DateTimeField(blank=True, null=True, verbose_name='면접 리포트 완성 거절 시각')),
        ('service_notice_opted_in_at', models.DateTimeField(blank=True, null=True, verbose_name='서비스 공지 동의 시각')),
        ('service_notice_opted_out_at', models.DateTimeField(blank=True, null=True, verbose_name='서비스 공지 거절 시각')),
        ('marketing_opted_in_at', models.DateTimeField(blank=True, null=True, verbose_name='마케팅 수신 동의 시각')),
        ('marketing_opted_out_at', models.DateTimeField(blank=True, null=True, verbose_name='마케팅 수신 거절 시각')),
        (
          'user',
          models.OneToOneField(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='email_notification_settings',
            to=settings.AUTH_USER_MODEL,
            verbose_name='사용자'
          )
        ),
      ],
      options={
        'verbose_name': '사용자 이메일 알림 설정',
        'verbose_name_plural': '사용자 이메일 알림 설정 목록',
        'db_table': 'user_email_notification_settings',
        'ordering': ['-created_at'],
        'get_latest_by': 'created_at',
        'abstract': False,
        'indexes': [
          models.Index(fields=['-created_at'], name='user_email__created_bf9054_idx'),
          models.Index(fields=['-updated_at'], name='user_email__updated_645d8f_idx')
        ],
        'constraints': [
          models.CheckConstraint(
            condition=models.Q(
              ('streak_reminder_opted_in_at__isnull', True), ('streak_reminder_opted_out_at__isnull', True),
              _connector='OR'
            ),
            name='user_email_notif_streak_reminder_xor'
          ),
          models.CheckConstraint(
            condition=models.Q(
              ('streak_expire_opted_in_at__isnull', True), ('streak_expire_opted_out_at__isnull', True),
              _connector='OR'
            ),
            name='user_email_notif_streak_expire_xor'
          ),
          models.CheckConstraint(
            condition=models.Q(
              ('report_ready_opted_in_at__isnull', True), ('report_ready_opted_out_at__isnull', True), _connector='OR'
            ),
            name='user_email_notif_report_ready_xor'
          ),
          models.CheckConstraint(
            condition=models.Q(
              ('service_notice_opted_in_at__isnull', True), ('service_notice_opted_out_at__isnull', True),
              _connector='OR'
            ),
            name='user_email_notif_service_notice_xor'
          ),
          models.CheckConstraint(
            condition=models.Q(
              ('marketing_opted_in_at__isnull', True), ('marketing_opted_out_at__isnull', True), _connector='OR'
            ),
            name='user_email_notif_marketing_xor'
          )
        ],
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
  ]
