# Generated by Django 6.0.3 on 2026-04-07 02:35

import uuid

import common.models.base_model
import common.models.base_model_with_soft_delete
import django.db.models.deletion
import pgvector.django.vector
import resumes.models.file_resume
import resumes.models.text_resume
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

  initial = True

  dependencies = [
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name='Resume',
      fields=[
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('deleted_at', models.DateTimeField(blank=True, null=True)),
        ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        (
          'type',
          models.CharField(
            choices=[('text', '자유 텍스트'), ('file', '파일 업로드'), ('structured', '정규화 입력')], db_column='type', max_length=20
          )
        ),
        ('title', models.CharField(max_length=255)),
        ('is_active', models.BooleanField(default=True)),
        ('is_parsed', models.BooleanField(default=False)),
        ('parsed_data', models.JSONField(blank=True, null=True)),
        (
          'analysis_status',
          models.CharField(
            choices=[('pending', '대기 중'), ('processing', '처리 중'), ('completed', '완료'), ('failed', '실패')],
            default='pending',
            max_length=20
          )
        ),
        (
          'analysis_step',
          models.CharField(
            choices=[
              ('queued', '큐 대기'), ('extracting_text', '텍스트 추출 중'), ('embedding', '임베딩 생성 중'), ('analyzing', 'LLM 분석 중'),
              ('finalizing', '최종 처리 중'), ('done', '완료')
            ],
            default='queued',
            max_length=30
          )
        ),
        ('analyzed_at', models.DateTimeField(blank=True, null=True)),
        (
          'user',
          models.ForeignKey(
            db_column='user_id',
            on_delete=django.db.models.deletion.CASCADE,
            related_name='resumes',
            to=settings.AUTH_USER_MODEL
          )
        ),
      ],
      options={
        'verbose_name': 'Resume',
        'verbose_name_plural': 'Resumes',
        'db_table': 'resumes',
        'abstract': False,
      },
      managers=[
        ('objects', common.models.base_model_with_soft_delete.SoftDeleteManager()),
        ('all_objects', common.models.base_model_with_soft_delete.AllObjectsManager()),
      ],
    ),
    migrations.CreateModel(
      name='FileResume',
      fields=[],
      options={
        'verbose_name': 'File Resume',
        'verbose_name_plural': 'File Resumes',
        'proxy': True,
        'indexes': [],
        'constraints': [],
      },
      bases=('resumes.resume', ),
      managers=[
        ('objects', resumes.models.file_resume.FileResumeManager()),
        ('all_objects', common.models.base_model_with_soft_delete.AllObjectsManager()),
      ],
    ),
    migrations.CreateModel(
      name='TextResume',
      fields=[],
      options={
        'verbose_name': 'Text Resume',
        'verbose_name_plural': 'Text Resumes',
        'proxy': True,
        'indexes': [],
        'constraints': [],
      },
      bases=('resumes.resume', ),
      managers=[
        ('objects', resumes.models.text_resume.TextResumeManager()),
        ('all_objects', common.models.base_model_with_soft_delete.AllObjectsManager()),
      ],
    ),
    migrations.CreateModel(
      name='ResumeEmbedding',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('deleted_at', models.DateTimeField(blank=True, null=True)),
        ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
        ('embedding_vector', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
        ('context', models.TextField(help_text='임베딩 대상 텍스트 청크 원문')),
        (
          'chunk_type',
          models.CharField(
            choices=[('text', '텍스트 청크'), ('keyword', '키워드 요약'), ('skill', '기술 스택'), ('career', '경력 요약')],
            default='text',
            max_length=20
          )
        ),
        ('chunk_index', models.IntegerField(default=0, help_text='청크 순서 (0-based)')),
        (
          'resume',
          models.ForeignKey(
            db_column='resume_id',
            on_delete=django.db.models.deletion.CASCADE,
            related_name='embeddings',
            to='resumes.resume'
          )
        ),
        (
          'user',
          models.ForeignKey(
            db_column='user_id',
            on_delete=django.db.models.deletion.CASCADE,
            related_name='resume_embeddings',
            to=settings.AUTH_USER_MODEL
          )
        ),
      ],
      options={
        'verbose_name': 'Resume Embedding',
        'verbose_name_plural': 'Resume Embeddings',
        'db_table': 'resume_embeddings',
        'abstract': False,
      },
      managers=[
        ('objects', common.models.base_model_with_soft_delete.SoftDeleteManager()),
        ('all_objects', common.models.base_model_with_soft_delete.AllObjectsManager()),
      ],
    ),
    migrations.CreateModel(
      name='SearchPlaygroundProxy',
      fields=[],
      options={
        'verbose_name': '검색 플레이그라운드',
        'verbose_name_plural': '검색 플레이그라운드',
        'proxy': True,
        'indexes': [],
        'constraints': [],
      },
      bases=('resumes.resumeembedding', ),
      managers=[
        ('objects', common.models.base_model_with_soft_delete.SoftDeleteManager()),
        ('all_objects', common.models.base_model_with_soft_delete.AllObjectsManager()),
      ],
    ),
    migrations.CreateModel(
      name='ResumeFileContent',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('deleted_at', models.DateTimeField(blank=True, null=True)),
        ('original_filename', models.CharField(max_length=255)),
        ('storage_path', models.CharField(max_length=500)),
        ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
        ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
        ('content', models.TextField(blank=True, null=True)),
        (
          'resume',
          models.OneToOneField(
            on_delete=django.db.models.deletion.CASCADE, related_name='file_content', to='resumes.resume'
          )
        ),
        (
          'user',
          models.ForeignKey(
            db_column='user_id',
            on_delete=django.db.models.deletion.CASCADE,
            related_name='resume_file_contents',
            to=settings.AUTH_USER_MODEL
          )
        ),
      ],
      options={
        'verbose_name': 'Resume File Content',
        'verbose_name_plural': 'Resume File Contents',
        'db_table': 'resume_file_contents',
        'abstract': False,
      },
      managers=[
        ('objects', common.models.base_model_with_soft_delete.SoftDeleteManager()),
        ('all_objects', common.models.base_model_with_soft_delete.AllObjectsManager()),
      ],
    ),
    migrations.CreateModel(
      name='ResumeTextContent',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('deleted_at', models.DateTimeField(blank=True, null=True)),
        ('content', models.TextField()),
        (
          'resume',
          models.OneToOneField(
            on_delete=django.db.models.deletion.CASCADE, related_name='text_content', to='resumes.resume'
          )
        ),
        (
          'user',
          models.ForeignKey(
            db_column='user_id',
            on_delete=django.db.models.deletion.CASCADE,
            related_name='resume_text_contents',
            to=settings.AUTH_USER_MODEL
          )
        ),
      ],
      options={
        'verbose_name': 'Resume Text Content',
        'verbose_name_plural': 'Resume Text Contents',
        'db_table': 'resume_text_contents',
        'abstract': False,
      },
      managers=[
        ('objects', common.models.base_model_with_soft_delete.SoftDeleteManager()),
        ('all_objects', common.models.base_model_with_soft_delete.AllObjectsManager()),
      ],
    ),
    migrations.CreateModel(
      name='ResumeTokenUsage',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        (
          'operation_type',
          models.CharField(choices=[('embed', '임베딩'), ('search', '검색 쿼리 임베딩'), ('analyze', 'LLM 분석')], max_length=20)
        ),
        ('model_name', models.CharField(max_length=100)),
        ('prompt_tokens', models.IntegerField(default=0)),
        ('total_tokens', models.IntegerField(default=0)),
        (
          'resume',
          models.ForeignKey(
            blank=True,
            db_column='resume_id',
            null=True,
            on_delete=django.db.models.deletion.SET_NULL,
            related_name='token_usages',
            to='resumes.resume'
          )
        ),
        (
          'user',
          models.ForeignKey(
            db_column='user_id',
            on_delete=django.db.models.deletion.CASCADE,
            related_name='resume_token_usages',
            to=settings.AUTH_USER_MODEL
          )
        ),
      ],
      options={
        'verbose_name': 'Resume Token Usage',
        'verbose_name_plural': 'Resume Token Usages',
        'db_table': 'resume_token_usages',
        'ordering': ['-created_at'],
        'get_latest_by': 'created_at',
        'abstract': False,
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
    migrations.AddIndex(
      model_name='resume',
      index=models.Index(fields=['deleted_at'], name='resumes_deleted_aa780d_idx'),
    ),
    migrations.AddIndex(
      model_name='resumeembedding',
      index=models.Index(fields=['deleted_at'], name='resume_embe_deleted_feb6ca_idx'),
    ),
    migrations.AddIndex(
      model_name='resumeembedding',
      index=models.Index(fields=['resume_id'], name='resume_emb_resume_idx'),
    ),
    migrations.AddIndex(
      model_name='resumeembedding',
      index=models.Index(fields=['user_id'], name='resume_emb_user_idx'),
    ),
    migrations.AddIndex(
      model_name='resumefilecontent',
      index=models.Index(fields=['-created_at'], name='resume_file_created_ffab48_idx'),
    ),
    migrations.AddIndex(
      model_name='resumetextcontent',
      index=models.Index(fields=['deleted_at'], name='resume_text_deleted_c48362_idx'),
    ),
    migrations.AddIndex(
      model_name='resumetokenusage',
      index=models.Index(fields=['-created_at'], name='resume_toke_created_9a0af0_idx'),
    ),
    migrations.AddIndex(
      model_name='resumetokenusage',
      index=models.Index(fields=['-updated_at'], name='resume_toke_updated_1e46f6_idx'),
    ),
    migrations.AddIndex(
      model_name='resumetokenusage',
      index=models.Index(fields=['user_id'], name='resume_tu_user_idx'),
    ),
    migrations.AddIndex(
      model_name='resumetokenusage',
      index=models.Index(fields=['resume_id'], name='resume_tu_resume_idx'),
    ),
    migrations.AddIndex(
      model_name='resumetokenusage',
      index=models.Index(fields=['operation_type'], name='resume_tu_op_idx'),
    ),
  ]
