# Generated by Django 6.0.3 on 2026-04-06 08:57

import common.models.base_model_with_soft_delete
from django.db import migrations


class Migration(migrations.Migration):

  dependencies = [
    ('resumes', '0001_initial'),
  ]

  operations = [
    migrations.CreateModel(
      name='SearchPlaygroundProxy',
      fields=[],
      options={
        'verbose_name': '검색 플레이그라운드',
        'verbose_name_plural': '검색 플레이그라운드',
        'proxy': True,
        'indexes': [],
        'constraints': [],
      },
      bases=('resumes.resumeembedding', ),
      managers=[
        ('objects', common.models.base_model_with_soft_delete.SoftDeleteManager()),
        ('all_objects', common.models.base_model_with_soft_delete.AllObjectsManager()),
      ],
    ),
  ]
