# Generated by Django 6.0.3 on 2026-04-14 13:32

import uuid

import common.models.base_model
import common.models.base_model_with_soft_delete
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('profiles', '0002_profile_avatar'),
    ('resumes', '0001_initial'),
  ]

  operations = [
    migrations.CreateModel(
      name='IndustryDomain',
      fields=[
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        ('name', models.CharField(max_length=100, unique=True, verbose_name='도메인명')),
      ],
      options={
        'verbose_name': '산업 도메인',
        'verbose_name_plural': '산업 도메인',
        'db_table': 'industry_domains',
        'ordering': ['name'],
        'abstract': False,
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
    migrations.CreateModel(
      name='Keyword',
      fields=[
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        ('text', models.CharField(max_length=100, unique=True, verbose_name='키워드')),
      ],
      options={
        'verbose_name': '이력서 키워드',
        'verbose_name_plural': '이력서 키워드',
        'db_table': 'keywords',
        'ordering': ['text'],
        'abstract': False,
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
    migrations.CreateModel(
      name='ResumeJobCategory',
      fields=[
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('deleted_at', models.DateTimeField(blank=True, null=True)),
        ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        (
          'name',
          models.CharField(help_text='IT, 마케팅, 디자인, 금융 등의 대분류', max_length=100, unique=True, verbose_name='분류명')
        ),
        ('emoji', models.CharField(blank=True, default='', max_length=10, verbose_name='이모지')),
        ('description', models.TextField(blank=True, default='', verbose_name='설명')),
      ],
      options={
        'verbose_name': '이력서 직군 분류',
        'verbose_name_plural': '이력서 직군 분류',
        'db_table': 'resume_job_categories',
        'ordering': ['name'],
      },
      managers=[
        ('objects', common.models.base_model_with_soft_delete.SoftDeleteManager()),
        ('all_objects', common.models.base_model_with_soft_delete.AllObjectsManager()),
      ],
    ),
    migrations.CreateModel(
      name='TechStack',
      fields=[
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        ('name', models.CharField(max_length=100, unique=True, verbose_name='기술명')),
      ],
      options={
        'verbose_name': '기술 스택',
        'verbose_name_plural': '기술 스택',
        'db_table': 'tech_stacks',
        'ordering': ['name'],
        'abstract': False,
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
    migrations.AddField(
      model_name='resume',
      name='is_dirty',
      field=models.BooleanField(
        default=False, help_text='정규화 sub-model 이 수정됐으나 최종 저장(재임베딩) 전 상태', verbose_name='변경 대기 상태'
      ),
    ),
    migrations.AddField(
      model_name='resume',
      name='last_finalized_at',
      field=models.DateTimeField(
        blank=True, help_text="사용자가 '최종 저장'을 눌러 재임베딩이 수행된 최근 시각", null=True, verbose_name='마지막 최종 저장 시각'
      ),
    ),
    migrations.AddField(
      model_name='resume',
      name='source_mode',
      field=models.CharField(
        choices=[('file', '파일 업로드'), ('text', '텍스트 입력'), ('structured', '구조화 폼 직접 작성')],
        default='text',
        help_text='이력서가 처음 생성된 방식: file / text / structured',
        max_length=20,
        verbose_name='원본 입력 방식'
      ),
    ),
    migrations.AlterField(
      model_name='resumeembedding',
      name='chunk_type',
      field=models.CharField(
        choices=[
          ('text', '텍스트 청크'), ('summary', '요약'), ('basic_info', '기본 정보'), ('skill', '스킬'), ('experience', '경력'),
          ('education', '학력'), ('certification', '자격증'), ('award', '수상 이력'), ('project', '프로젝트'),
          ('language_spoken', '구사 언어'), ('industry_domain', '산업 도메인'), ('keyword', '키워드')
        ],
        default='text',
        max_length=20
      ),
    ),
    migrations.AddField(
      model_name='resume',
      name='resume_job_category',
      field=models.ForeignKey(
        blank=True,
        null=True,
        on_delete=django.db.models.deletion.SET_NULL,
        related_name='resumes',
        to='resumes.resumejobcategory',
        verbose_name='감지된 이력서 직군 분류'
      ),
    ),
    migrations.CreateModel(
      name='ResumeProject',
      fields=[
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('deleted_at', models.DateTimeField(blank=True, null=True)),
        ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        ('name', models.CharField(blank=True, default='', max_length=200)),
        ('role', models.CharField(blank=True, default='', max_length=100)),
        ('period', models.CharField(blank=True, default='', max_length=100)),
        ('description', models.TextField(blank=True, default='')),
        ('display_order', models.PositiveIntegerField(default=0)),
        (
          'resume',
          models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='resumes.resume')
        ),
      ],
      options={
        'verbose_name': '이력서 프로젝트',
        'verbose_name_plural': '이력서 프로젝트',
        'db_table': 'resume_projects',
        'ordering': ['display_order', 'created_at'],
        'abstract': False,
      },
      managers=[
        ('objects', common.models.base_model_with_soft_delete.SoftDeleteManager()),
        ('all_objects', common.models.base_model_with_soft_delete.AllObjectsManager()),
      ],
    ),
    migrations.CreateModel(
      name='ResumeTextContentTemplate',
      fields=[
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('deleted_at', models.DateTimeField(blank=True, null=True)),
        ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        ('title', models.CharField(help_text="예: '신입 프론트엔드 개발자 템플릿'", max_length=100, verbose_name='템플릿 제목')),
        ('content', models.TextField(help_text='사용자가 이력서 작성을 시작할 때 pre-fill 되는 텍스트', verbose_name='템플릿 본문')),
        ('display_order', models.IntegerField(default=0, help_text='같은 직업 내에서 정렬 기준', verbose_name='표시 순서')),
        (
          'job',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='resume_text_content_templates',
            to='profiles.job',
            verbose_name='직업'
          )
        ),
      ],
      options={
        'verbose_name': '이력서 텍스트 템플릿',
        'verbose_name_plural': '이력서 텍스트 템플릿',
        'db_table': 'resume_text_content_templates',
        'ordering': ['job__name', 'display_order', 'title'],
      },
      managers=[
        ('objects', common.models.base_model_with_soft_delete.SoftDeleteManager()),
        ('all_objects', common.models.base_model_with_soft_delete.AllObjectsManager()),
      ],
    ),
    migrations.CreateModel(
      name='Skill',
      fields=[
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        ('name', models.CharField(max_length=100, verbose_name='스킬명')),
        (
          'skill_type',
          models.CharField(
            choices=[('technical', '기술'), ('soft', '소프트'), ('tool', '도구'), ('language', '언어')],
            max_length=20,
            verbose_name='스킬 분류'
          )
        ),
      ],
      options={
        'verbose_name': '이력서 스킬',
        'verbose_name_plural': '이력서 스킬',
        'db_table': 'skills',
        'ordering': ['skill_type', 'name'],
        'abstract': False,
        'indexes': [models.Index(fields=['skill_type', 'name'], name='skills_skill_t_55458e_idx')],
        'constraints': [models.UniqueConstraint(fields=('name', 'skill_type'), name='uniq_resumes_skill_name_type')],
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
    migrations.CreateModel(
      name='ResumeProjectTechStack',
      fields=[
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('deleted_at', models.DateTimeField(blank=True, null=True)),
        ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        ('display_order', models.PositiveIntegerField(default=0)),
        (
          'resume_project',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='resume_project_tech_stacks',
            to='resumes.resumeproject'
          )
        ),
        (
          'tech_stack',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='resume_project_tech_stacks',
            to='resumes.techstack'
          )
        ),
      ],
      options={
        'verbose_name': '이력서 프로젝트 기술 스택 매핑',
        'verbose_name_plural': '이력서 프로젝트 기술 스택 매핑',
        'db_table': 'resume_project_tech_stacks',
        'ordering': ['display_order', 'created_at'],
        'abstract': False,
      },
      managers=[
        ('objects', common.models.base_model_with_soft_delete.SoftDeleteManager()),
        ('all_objects', common.models.base_model_with_soft_delete.AllObjectsManager()),
      ],
    ),
    migrations.AddField(
      model_name='resumeproject',
      name='tech_stacks',
      field=models.ManyToManyField(
        related_name='resume_projects', through='resumes.ResumeProjectTechStack', to='resumes.techstack'
      ),
    ),
    migrations.CreateModel(
      name='ResumeAward',
      fields=[
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('deleted_at', models.DateTimeField(blank=True, null=True)),
        ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        ('name', models.CharField(blank=True, default='', max_length=200)),
        ('year', models.CharField(blank=True, default='', max_length=20)),
        ('organization', models.CharField(blank=True, default='', max_length=200)),
        ('description', models.TextField(blank=True, default='')),
        ('display_order', models.PositiveIntegerField(default=0)),
        (
          'resume',
          models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='resumes.resume')
        ),
      ],
      options={
        'verbose_name': '이력서 수상 이력',
        'verbose_name_plural': '이력서 수상 이력',
        'db_table': 'resume_awards',
        'ordering': ['display_order', 'created_at'],
        'abstract': False,
        'indexes': [models.Index(fields=['resume', 'display_order'], name='resume_awar_resume__2c8ad2_idx')],
      },
      managers=[
        ('objects', common.models.base_model_with_soft_delete.SoftDeleteManager()),
        ('all_objects', common.models.base_model_with_soft_delete.AllObjectsManager()),
      ],
    ),
    migrations.CreateModel(
      name='ResumeBasicInfo',
      fields=[
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('deleted_at', models.DateTimeField(blank=True, null=True)),
        ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        ('name', models.CharField(blank=True, default='', max_length=100)),
        ('email', models.EmailField(blank=True, default='', max_length=254)),
        ('phone', models.CharField(blank=True, default='', max_length=50)),
        ('location', models.CharField(blank=True, default='', max_length=200)),
        (
          'resume',
          models.OneToOneField(
            on_delete=django.db.models.deletion.CASCADE, related_name='basic_info', to='resumes.resume'
          )
        ),
      ],
      options={
        'verbose_name': '이력서 기본 정보',
        'verbose_name_plural': '이력서 기본 정보',
        'db_table': 'resume_basic_infos',
        'abstract': False,
        'indexes': [models.Index(fields=['deleted_at'], name='resume_basi_deleted_96e374_idx')],
      },
      managers=[
        ('objects', common.models.base_model_with_soft_delete.SoftDeleteManager()),
        ('all_objects', common.models.base_model_with_soft_delete.AllObjectsManager()),
      ],
    ),
    migrations.CreateModel(
      name='ResumeCareerMeta',
      fields=[
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('deleted_at', models.DateTimeField(blank=True, null=True)),
        ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        ('total_experience_years', models.PositiveIntegerField(blank=True, null=True)),
        ('total_experience_months', models.PositiveIntegerField(blank=True, null=True)),
        (
          'resume',
          models.OneToOneField(
            on_delete=django.db.models.deletion.CASCADE, related_name='career_meta', to='resumes.resume'
          )
        ),
      ],
      options={
        'verbose_name': '이력서 경력 메타',
        'verbose_name_plural': '이력서 경력 메타',
        'db_table': 'resume_career_metas',
        'abstract': False,
        'indexes': [models.Index(fields=['deleted_at'], name='resume_care_deleted_476eb1_idx')],
      },
      managers=[
        ('objects', common.models.base_model_with_soft_delete.SoftDeleteManager()),
        ('all_objects', common.models.base_model_with_soft_delete.AllObjectsManager()),
      ],
    ),
    migrations.CreateModel(
      name='ResumeCertification',
      fields=[
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('deleted_at', models.DateTimeField(blank=True, null=True)),
        ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        ('name', models.CharField(blank=True, default='', max_length=200)),
        ('issuer', models.CharField(blank=True, default='', max_length=200)),
        ('date', models.CharField(blank=True, default='', max_length=50)),
        ('display_order', models.PositiveIntegerField(default=0)),
        (
          'resume',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='resumes.resume'
          )
        ),
      ],
      options={
        'verbose_name': '이력서 자격증',
        'verbose_name_plural': '이력서 자격증',
        'db_table': 'resume_certifications',
        'ordering': ['display_order', 'created_at'],
        'abstract': False,
        'indexes': [models.Index(fields=['resume', 'display_order'], name='resume_cert_resume__0935fa_idx')],
      },
      managers=[
        ('objects', common.models.base_model_with_soft_delete.SoftDeleteManager()),
        ('all_objects', common.models.base_model_with_soft_delete.AllObjectsManager()),
      ],
    ),
    migrations.CreateModel(
      name='ResumeEducation',
      fields=[
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('deleted_at', models.DateTimeField(blank=True, null=True)),
        ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        ('school', models.CharField(blank=True, default='', max_length=200)),
        ('degree', models.CharField(blank=True, default='', max_length=100)),
        ('major', models.CharField(blank=True, default='', max_length=200)),
        ('period', models.CharField(blank=True, default='', max_length=100)),
        ('display_order', models.PositiveIntegerField(default=0)),
        (
          'resume',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='resumes.resume'
          )
        ),
      ],
      options={
        'verbose_name': '이력서 학력',
        'verbose_name_plural': '이력서 학력',
        'db_table': 'resume_educations',
        'ordering': ['display_order', 'created_at'],
        'abstract': False,
        'indexes': [models.Index(fields=['resume', 'display_order'], name='resume_educ_resume__3bfd65_idx')],
      },
      managers=[
        ('objects', common.models.base_model_with_soft_delete.SoftDeleteManager()),
        ('all_objects', common.models.base_model_with_soft_delete.AllObjectsManager()),
      ],
    ),
    migrations.CreateModel(
      name='ResumeExperience',
      fields=[
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('deleted_at', models.DateTimeField(blank=True, null=True)),
        ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        ('company', models.CharField(blank=True, default='', max_length=200)),
        ('role', models.CharField(blank=True, default='', max_length=200)),
        ('period', models.CharField(blank=True, default='', max_length=100)),
        (
          'responsibilities',
          django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list)
        ),
        (
          'highlights',
          django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list)
        ),
        ('display_order', models.PositiveIntegerField(default=0)),
        (
          'resume',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='resumes.resume'
          )
        ),
      ],
      options={
        'verbose_name': '이력서 경력',
        'verbose_name_plural': '이력서 경력',
        'db_table': 'resume_experiences',
        'ordering': ['display_order', 'created_at'],
        'abstract': False,
        'indexes': [models.Index(fields=['resume', 'display_order'], name='resume_expe_resume__2401b3_idx')],
      },
      managers=[
        ('objects', common.models.base_model_with_soft_delete.SoftDeleteManager()),
        ('all_objects', common.models.base_model_with_soft_delete.AllObjectsManager()),
      ],
    ),
    migrations.CreateModel(
      name='ResumeIndustryDomain',
      fields=[
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('deleted_at', models.DateTimeField(blank=True, null=True)),
        ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        ('display_order', models.PositiveIntegerField(default=0)),
        (
          'industry_domain',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='resume_industry_domains',
            to='resumes.industrydomain'
          )
        ),
        (
          'resume',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE, related_name='resume_industry_domains', to='resumes.resume'
          )
        ),
      ],
      options={
        'verbose_name': '이력서 산업 도메인 매핑',
        'verbose_name_plural': '이력서 산업 도메인 매핑',
        'db_table': 'resume_industry_domains',
        'ordering': ['display_order', 'created_at'],
        'abstract': False,
        'indexes': [models.Index(fields=['deleted_at'], name='resume_indu_deleted_e4cfd8_idx')],
        'constraints': [
          models.UniqueConstraint(
            condition=models.Q(('deleted_at__isnull', True)),
            fields=('resume', 'industry_domain'),
            name='uniq_resume_industry_domain_active'
          )
        ],
      },
      managers=[
        ('objects', common.models.base_model_with_soft_delete.SoftDeleteManager()),
        ('all_objects', common.models.base_model_with_soft_delete.AllObjectsManager()),
      ],
    ),
    migrations.CreateModel(
      name='ResumeKeyword',
      fields=[
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('deleted_at', models.DateTimeField(blank=True, null=True)),
        ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        ('display_order', models.PositiveIntegerField(default=0)),
        (
          'keyword',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE, related_name='resume_keywords', to='resumes.keyword'
          )
        ),
        (
          'resume',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE, related_name='resume_keywords', to='resumes.resume'
          )
        ),
      ],
      options={
        'verbose_name': '이력서 키워드 매핑',
        'verbose_name_plural': '이력서 키워드 매핑',
        'db_table': 'resume_keywords',
        'ordering': ['display_order', 'created_at'],
        'abstract': False,
        'indexes': [models.Index(fields=['deleted_at'], name='resume_keyw_deleted_da5a06_idx')],
        'constraints': [
          models.UniqueConstraint(
            condition=models.Q(('deleted_at__isnull', True)),
            fields=('resume', 'keyword'),
            name='uniq_resume_keyword_active'
          )
        ],
      },
      managers=[
        ('objects', common.models.base_model_with_soft_delete.SoftDeleteManager()),
        ('all_objects', common.models.base_model_with_soft_delete.AllObjectsManager()),
      ],
    ),
    migrations.CreateModel(
      name='ResumeLanguageSpoken',
      fields=[
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('deleted_at', models.DateTimeField(blank=True, null=True)),
        ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        ('language', models.CharField(blank=True, default='', max_length=100)),
        ('level', models.CharField(blank=True, default='', max_length=100)),
        ('display_order', models.PositiveIntegerField(default=0)),
        (
          'resume',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE, related_name='languages_spoken', to='resumes.resume'
          )
        ),
      ],
      options={
        'verbose_name': '이력서 구사 언어',
        'verbose_name_plural': '이력서 구사 언어',
        'db_table': 'resume_languages_spoken',
        'ordering': ['display_order', 'created_at'],
        'abstract': False,
        'indexes': [models.Index(fields=['resume', 'display_order'], name='resume_lang_resume__b5cec6_idx')],
      },
      managers=[
        ('objects', common.models.base_model_with_soft_delete.SoftDeleteManager()),
        ('all_objects', common.models.base_model_with_soft_delete.AllObjectsManager()),
      ],
    ),
    migrations.CreateModel(
      name='ResumeSummary',
      fields=[
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('deleted_at', models.DateTimeField(blank=True, null=True)),
        ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        ('text', models.TextField(blank=True, default='')),
        (
          'resume',
          models.OneToOneField(
            on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='resumes.resume'
          )
        ),
      ],
      options={
        'verbose_name': '이력서 요약',
        'verbose_name_plural': '이력서 요약',
        'db_table': 'resume_summaries',
        'abstract': False,
        'indexes': [models.Index(fields=['deleted_at'], name='resume_summ_deleted_fe306c_idx')],
      },
      managers=[
        ('objects', common.models.base_model_with_soft_delete.SoftDeleteManager()),
        ('all_objects', common.models.base_model_with_soft_delete.AllObjectsManager()),
      ],
    ),
    migrations.CreateModel(
      name='ResumeSkill',
      fields=[
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('deleted_at', models.DateTimeField(blank=True, null=True)),
        ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        ('display_order', models.PositiveIntegerField(default=0)),
        (
          'resume',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE, related_name='resume_skills', to='resumes.resume'
          )
        ),
        (
          'skill',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE, related_name='resume_skills', to='resumes.skill'
          )
        ),
      ],
      options={
        'verbose_name': '이력서 스킬 매핑',
        'verbose_name_plural': '이력서 스킬 매핑',
        'db_table': 'resume_skills',
        'ordering': ['display_order', 'created_at'],
        'abstract': False,
        'indexes': [models.Index(fields=['resume', 'display_order'], name='resume_skil_resume__625507_idx')],
        'constraints': [
          models.UniqueConstraint(
            condition=models.Q(('deleted_at__isnull', True)),
            fields=('resume', 'skill'),
            name='uniq_resume_skill_active'
          )
        ],
      },
      managers=[
        ('objects', common.models.base_model_with_soft_delete.SoftDeleteManager()),
        ('all_objects', common.models.base_model_with_soft_delete.AllObjectsManager()),
      ],
    ),
    migrations.AddIndex(
      model_name='resumeprojecttechstack',
      index=models.Index(fields=['deleted_at'], name='resume_proj_deleted_2f38e1_idx'),
    ),
    migrations.AddConstraint(
      model_name='resumeprojecttechstack',
      constraint=models.UniqueConstraint(
        condition=models.Q(('deleted_at__isnull', True)),
        fields=('resume_project', 'tech_stack'),
        name='uniq_resume_project_tech_stack_active'
      ),
    ),
    migrations.AddIndex(
      model_name='resumeproject',
      index=models.Index(fields=['resume', 'display_order'], name='resume_proj_resume__0a953b_idx'),
    ),
  ]
