# Generated by Django 6.0.3 on 2026-04-15 17:27

from django.db import migrations


class Migration(migrations.Migration):

  dependencies = [
    ('resumes', '0002_industrydomain_keyword_resumejobcategory_techstack_and_more'),
  ]

  operations = [
    migrations.RemoveField(
      model_name='resume',
      name='is_active',
    ),
  ]
