x-celery-base: &celery-base
  build:
    context: .
    dockerfile: ./environments/development/Dockerfile
  restart: always
  env_file:
    - .env
  environment:
    - DJANGO_SETTINGS_MODULE=config.settings.development
  volumes:
    - ./webapp:/app/webapp
    - ./environments/development/entrypoint.sh:/app/entrypoint.sh
  entrypoint: []

x-postgres-base: &postgres-base
  build:
    context: .
    dockerfile: ./environments/development/Dockerfile.postgres
  healthcheck:
    interval: 10s
    timeout: 5s
    retries: 5

services:
  webapp:
    build:
      context: .
      dockerfile: ./environments/development/Dockerfile
    command: uvicorn config.asgi:application --host 0.0.0.0 --port ${PORT} --reload
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./webapp:/app/webapp
      - ./environments/development/entrypoint.sh:/app/entrypoint.sh
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      test_postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    <<: *postgres-base
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./environments/development/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${DATABASE_NAME}"]

  test_postgres:
    <<: *postgres-base
    ports:
      - ${TEST_POSTGRES_PORT}:5432
    volumes:
      - test_postgres_data:/var/lib/postgresql
      - ./environments/development/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      POSTGRES_DB: ${TEST_DATABASE_NAME}
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TEST_POSTGRES_USER} -d ${TEST_DATABASE_NAME}"]

  redis:
    image: redis:8
    container_name: mefit-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  celery-worker:
    <<: *celery-base
    container_name: mefit-celery-worker
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: celery -A config worker -l INFO

  celery-beat:
    <<: *celery-base
    container_name: mefit-celery-beat
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: celery -A config beat -l INFO

volumes:
  postgres_data:
  test_postgres_data:
