# Generated by Django 6.0.3 on 2026-03-28 09:35

import common.models.base_model_with_soft_delete
import django.db.models.deletion
import profiles.models.job
import profiles.models.job_category
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

  initial = True

  dependencies = [
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name='JobCategory',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('deleted_at', models.DateTimeField(blank=True, null=True)),
        ('emoji', models.CharField(max_length=10)),
        ('name', models.CharField(max_length=100)),
        ('opened_at', models.DateTimeField(blank=True, help_text='사용자에게 공개된 시간', null=True, verbose_name='오픈 일시')),
      ],
      options={
        'verbose_name': 'Job Category',
        'verbose_name_plural': 'Job Categories',
        'db_table': 'job_categories',
        'ordering': ['name'],
        'constraints': [
          models.UniqueConstraint(
            condition=models.Q(('deleted_at__isnull', True)),
            fields=('name', ),
            name='unique_job_category_name_when_not_deleted'
          )
        ],
      },
      managers=[
        ('objects', profiles.models.job_category.JobCategoryManager()),
        ('all_objects', profiles.models.job_category.JobCategoryAllObjectsManager()),
      ],
    ),
    migrations.CreateModel(
      name='Job',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('deleted_at', models.DateTimeField(blank=True, null=True)),
        ('name', models.CharField(max_length=100)),
        ('opened_at', models.DateTimeField(blank=True, help_text='사용자에게 공개된 시간', null=True, verbose_name='오픈 일시')),
        (
          'category',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='profiles.jobcategory'
          )
        ),
      ],
      options={
        'verbose_name': 'Job',
        'verbose_name_plural': 'Jobs',
        'db_table': 'jobs',
        'ordering': ['name'],
      },
      managers=[
        ('objects', profiles.models.job.JobManager()),
        ('all_objects', profiles.models.job.JobAllObjectsManager()),
      ],
    ),
    migrations.CreateModel(
      name='Profile',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('deleted_at', models.DateTimeField(blank=True, null=True)),
        (
          'job_category',
          models.ForeignKey(
            on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='profiles.jobcategory'
          )
        ),
        ('jobs', models.ManyToManyField(related_name='profiles', to='profiles.job')),
        (
          'user',
          models.OneToOneField(
            on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL
          )
        ),
      ],
      options={
        'verbose_name': 'Profile',
        'verbose_name_plural': 'Profiles',
        'db_table': 'profiles',
      },
      managers=[
        ('objects', common.models.base_model_with_soft_delete.SoftDeleteManager()),
        ('all_objects', common.models.base_model_with_soft_delete.AllObjectsManager()),
      ],
    ),
    migrations.AddIndex(
      model_name='job',
      index=models.Index(fields=['category', 'name'], name='jobs_categor_a9e71d_idx'),
    ),
  ]
