# Generated by Django 6.0.3 on 2026-04-03 15:27

import profiles.models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('profiles', '0001_initial'),
  ]

  operations = [
    migrations.AddField(
      model_name='profile',
      name='avatar',
      field=models.ImageField(blank=True, null=True, upload_to=profiles.models.profile.avatar_upload_to),
    ),
  ]
