# Generated by Django 6.0.3 on 2026-04-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('profiles', '0002_profile_avatar'),
  ]

  operations = [
    migrations.AddField(
      model_name='profile',
      name='career_stage',
      field=models.CharField(
        choices=[
          ('university_student', '대학생'), ('graduate_student', '대학원생'), ('lt_1_year', '1년 미만'), ('1_3_years', '1-3년'),
          ('3_7_years', '3-7년'), ('over_7_years', '7년 이상'), ('other', '기타')
        ],
        default='other',
        max_length=20
      ),
    ),
  ]
