apiVersion: apps/v1
kind: Deployment
metadata:
  name: mefit-production-redis
  namespace: mefit-backend-production
  labels:
    app: mefit-production-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mefit-production-redis
  template:
    metadata:
      labels:
        app: mefit-production-redis
    spec:
      containers:
        - name: redis
          image: redis:8-alpine
          ports:
            - containerPort: 6379
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
