# Generated by Django 6.0.3 on 2026-04-08 12:34

import common.models.base_model
from django.db import migrations, models


class Migration(migrations.Migration):

  initial = True

  dependencies = []

  operations = [
    migrations.CreateModel(
      name='JobDescription',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('url', models.URLField(max_length=2048, unique=True, verbose_name='채용공고 URL')),
        (
          'platform',
          models.CharField(
            blank=True, default='', help_text='saramin, jobkorea, jobplanet 등', max_length=50, verbose_name='플랫폼명'
          )
        ),
        ('company', models.CharField(blank=True, default='', max_length=255, verbose_name='회사명')),
        ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='채용공고 제목')),
        ('duties', models.TextField(blank=True, default='', verbose_name='담당업무')),
        ('requirements', models.TextField(blank=True, default='', verbose_name='지원자격 / 필수조건')),
        ('preferred', models.TextField(blank=True, default='', verbose_name='우대사항')),
        (
          'work_type',
          models.CharField(blank=True, default='', help_text='정규직, 계약직, 인턴 등', max_length=50, verbose_name='고용형태')
        ),
        ('salary', models.CharField(blank=True, default='', max_length=255, verbose_name='급여 정보')),
        ('location', models.CharField(blank=True, default='', max_length=255, verbose_name='근무지역')),
        ('education', models.CharField(blank=True, default='', max_length=100, verbose_name='학력 조건')),
        ('experience', models.CharField(blank=True, default='', max_length=100, verbose_name='경력 조건')),
        (
          'collection_status',
          models.CharField(
            choices=[('pending', '수집 진행 예정'), ('in_progress', '수집 중'), ('done', '수집 완료'), ('error', '수집 실패')],
            default='pending',
            max_length=20,
            verbose_name='수집 상태'
          )
        ),
        ('scraped_at', models.DateTimeField(blank=True, null=True, verbose_name='수집 완료 일시')),
        ('error_message', models.TextField(blank=True, default='', verbose_name='에러 메시지')),
      ],
      options={
        'verbose_name': '채용공고',
        'verbose_name_plural': '채용공고 목록',
        'db_table': 'job_descriptions',
        'ordering': ['-created_at'],
        'get_latest_by': 'created_at',
        'abstract': False,
        'indexes': [
          models.Index(fields=['-created_at'], name='job_descrip_created_94c96e_idx'),
          models.Index(fields=['-updated_at'], name='job_descrip_updated_1c7e60_idx')
        ],
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
  ]
