# Generated by Django 6.0.3 on 2026-04-08 17:00

import uuid

import common.models.base_model
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('job_descriptions', '0001_initial'),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name='UserJobDescription',
      fields=[
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        (
          'job_description',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='user_job_descriptions',
            to='job_descriptions.jobdescription',
            verbose_name='채용공고'
          )
        ),
        (
          'user',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='user_job_descriptions',
            to=settings.AUTH_USER_MODEL,
            verbose_name='사용자'
          )
        ),
      ],
      options={
        'verbose_name': '사용자 채용공고',
        'verbose_name_plural': '사용자 채용공고 목록',
        'db_table': 'user_job_descriptions',
        'abstract': False,
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
  ]
