# Generated by Django 6.0.3 on 2026-04-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('job_descriptions', '0002_userjobdescription'),
  ]

  operations = [
    migrations.AddField(
      model_name='userjobdescription',
      name='application_status',
      field=models.CharField(
        choices=[('planned', '지원 예정'), ('saved', '관심 저장'), ('applied', '지원 완료')],
        default='planned',
        max_length=20,
        verbose_name='지원 상태'
      ),
    ),
  ]
