# Generated by Django 6.0.3 on 2026-04-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('job_descriptions', '0003_userjobdescription_application_status'),
  ]

  operations = [
    migrations.AddField(
      model_name='userjobdescription',
      name='title',
      field=models.CharField(
        blank=True, default='', help_text='사용자가 직접 지은 채용공고 식별 제목', max_length=255, verbose_name='내 식별 제목'
      ),
    ),
  ]
