"""면접 세션 설정 상수."""

from config.settings.base import (
  TICKET_COST_FOLLOWUP_INTERVIEW,
  TICKET_COST_FULL_PROCESS_INTERVIEW,
)

# 꼬리질문형(FOLLOWUP) 면접 설정
FOLLOWUP_ANCHOR_COUNT = 2  # 앵커 질문 수
MAX_FOLLOWUP_PER_ANCHOR = 3  # 앵커당 최대 꼬리질문 수
# 총 질문 수 = FOLLOWUP_ANCHOR_COUNT * (1 + MAX_FOLLOWUP_PER_ANCHOR) = 8

# 일반 프로세스(FULL_PROCESS) 면접 설정
FULL_PROCESS_QUESTION_COUNT = 10  # 자기소개~마무리 총 질문 수

# 티켓 소모량
TICKET_COST_FOLLOWUP = TICKET_COST_FOLLOWUP_INTERVIEW
TICKET_COST_FULL_PROCESS = TICKET_COST_FULL_PROCESS_INTERVIEW
