services:
  localstack:
    image: localstack/localstack:latest
    container_name: mefit-localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3,lambda,sns,sqs
      DEFAULT_REGION: us-east-1
      LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT: 300
      LAMBDA_DOCKER_NETWORK: mefit-local
    volumes:
      - "./localstack_init.sh:/etc/localstack/init/ready.d/init.sh"
      - "../functions:/opt/mefit/functions:ro"
      - "../layers:/opt/mefit/layers:ro"
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mefit-local

volumes:
  localstack_data:

networks:
  mefit-local:
    external: true
