# Generated by Django 6.0.3 on 2026-03-31 16:30

import common.models.base_model
import django.db.models.deletion
import terms_documents.models.terms_document
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

  initial = True

  dependencies = [
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name='TermsDocument',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        (
          'terms_type',
          models.CharField(
            choices=[
              ('terms_of_service', '이용약관'), ('privacy_policy', '개인정보처리방침'), ('ai_training_data', 'AI 학습 데이터 활용 동의')
            ],
            max_length=50,
            verbose_name='약관 유형'
          )
        ),
        ('version', models.PositiveIntegerField(editable=False, verbose_name='버전')),
        ('title', models.CharField(max_length=200, verbose_name='제목')),
        ('content', models.TextField(verbose_name='내용 (마크다운)')),
        ('is_required', models.BooleanField(default=True, verbose_name='필수 동의 여부')),
        ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='공개일시')),
        ('effective_at', models.DateTimeField(blank=True, null=True, verbose_name='적용일')),
      ],
      options={
        'verbose_name': '약관',
        'verbose_name_plural': '약관 목록',
        'ordering': ['terms_type', '-version'],
        'get_latest_by': 'created_at',
        'abstract': False,
        'indexes': [
          models.Index(fields=['-created_at'], name='terms_docum_created_3d996c_idx'),
          models.Index(fields=['-updated_at'], name='terms_docum_updated_e71057_idx')
        ],
        'constraints': [
          models.UniqueConstraint(
            condition=models.Q(('published_at__isnull', False)),
            fields=('terms_type', ),
            name='unique_published_terms_per_type'
          ),
          models.UniqueConstraint(fields=('terms_type', 'version'), name='unique_terms_type_version')
        ],
      },
      managers=[
        ('objects', terms_documents.models.terms_document.TermsDocumentManager()),
      ],
    ),
    migrations.CreateModel(
      name='UserConsent',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('agreed_at', models.DateTimeField(verbose_name='동의 일시')),
        (
          'terms_document',
          models.ForeignKey(
            on_delete=django.db.models.deletion.PROTECT,
            related_name='user_consents',
            to='terms_documents.termsdocument',
            verbose_name='약관'
          )
        ),
        (
          'user',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='terms_document_consents',
            to=settings.AUTH_USER_MODEL,
            verbose_name='사용자'
          )
        ),
      ],
      options={
        'verbose_name': '사용자 약관 동의',
        'verbose_name_plural': '사용자 약관 동의 목록',
        'ordering': ['-created_at'],
        'get_latest_by': 'created_at',
        'abstract': False,
        'indexes': [
          models.Index(fields=['-created_at'], name='terms_docum_created_0bf7e1_idx'),
          models.Index(fields=['-updated_at'], name='terms_docum_updated_fce7f5_idx')
        ],
        'constraints': [models.UniqueConstraint(fields=('user', 'terms_document'), name='unique_user_terms_consent')],
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
  ]
