# Generated by Django 6.0.3 on 2026-05-03 05:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('terms_documents', '0001_initial'),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.AddField(
      model_name='userconsent',
      name='disagreed_at',
      field=models.DateTimeField(blank=True, null=True, verbose_name='거절 일시'),
    ),
    migrations.AlterField(
      model_name='termsdocument',
      name='terms_type',
      field=models.CharField(
        choices=[
          ('terms_of_service', '이용약관'), ('privacy_policy', '개인정보처리방침'), ('ai_training_data', 'AI 학습 데이터 활용 동의'),
          ('marketing', '마케팅 정보 수신 동의')
        ],
        max_length=50,
        verbose_name='약관 유형'
      ),
    ),
    migrations.AlterField(
      model_name='userconsent',
      name='agreed_at',
      field=models.DateTimeField(blank=True, null=True, verbose_name='동의 일시'),
    ),
    migrations.AddConstraint(
      model_name='userconsent',
      constraint=models.CheckConstraint(
        condition=models.Q(('agreed_at__isnull', True), ('disagreed_at__isnull', True), _connector='OR'),
        name='user_consent_xor'
      ),
    ),
  ]
