# Generated by Django 6.0.3 on 2026-04-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ("interview", "0001_initial"),
  ]

  operations = [
    migrations.AddField(
      model_name="interviewsession",
      name="difficulty_level",
      field=models.CharField(
        choices=[
          ("friendly", "친절"),
          ("normal", "보통"),
          ("pressure", "압박"),
        ],
        default="normal",
        max_length=10,
      ),
    ),
  ]
