# Generated by Django 6.0.3 on 2026-04-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('interview', '0002_interviewsession_difficulty_level'),
  ]

  operations = [
    migrations.AddField(
      model_name='interviewsession',
      name='avg_answer_length',
      field=models.IntegerField(default=0, help_text='평균 답변 길이 (글자 수)'),
    ),
    migrations.AddField(
      model_name='interviewsession',
      name='duration_seconds',
      field=models.IntegerField(blank=True, help_text='총 소요 시간 (초)', null=True),
    ),
    migrations.AddField(
      model_name='interviewsession',
      name='finished_at',
      field=models.DateTimeField(blank=True, help_text='면접 종료 시간', null=True),
    ),
    migrations.AddField(
      model_name='interviewsession',
      name='job_posting_file',
      field=models.CharField(blank=True, default='', help_text='사용된 채용공고 파일명', max_length=255),
    ),
    migrations.AddField(
      model_name='interviewsession',
      name='resume_file',
      field=models.CharField(blank=True, default='', help_text='사용된 이력서 파일명', max_length=255),
    ),
    migrations.AddField(
      model_name='interviewsession',
      name='started_at',
      field=models.DateTimeField(blank=True, help_text='면접 시작 시간 (첫 질문 생성 완료 시점)', null=True),
    ),
    migrations.AddField(
      model_name='interviewsession',
      name='status',
      field=models.CharField(
        choices=[('in_progress', '진행 중'), ('completed', '완료'), ('abandoned', '중도 포기')],
        default='in_progress',
        max_length=15
      ),
    ),
    migrations.AddField(
      model_name='interviewsession',
      name='total_chunks_retrieved',
      field=models.IntegerField(default=0, help_text='RAG에서 검색된 총 청크 수'),
    ),
    migrations.AddField(
      model_name='interviewsession',
      name='total_followup_questions',
      field=models.IntegerField(default=0, help_text='꼬리질문 수'),
    ),
    migrations.AddField(
      model_name='interviewsession',
      name='total_initial_questions',
      field=models.IntegerField(default=0, help_text='메인 질문 수'),
    ),
  ]
