# Generated by Django 6.0.3 on 2026-04-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ("interview", "0003_interviewsession_avg_answer_length_and_more"),
  ]

  operations = [
    migrations.AddField(
      model_name="interviewexchange",
      name="question_purpose",
      field=models.CharField(
        blank=True,
        default="",
        help_text="질문 출제 목적 (꼬리질문의 rationale)",
        max_length=500,
      ),
    ),
    migrations.AddField(
      model_name="interviewexchange",
      name="question_source",
      field=models.CharField(
        blank=True,
        default="",
        help_text="질문 출처 (resume, job_posting)",
        max_length=20,
      ),
    ),
  ]
