# Generated by Django 6.0.3 on 2026-04-05 03:56

import common.models.base_model
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ("interview", "0004_interviewexchange_question_purpose_and_more"),
  ]

  operations = [
    migrations.CreateModel(
      name="AnalysisReport",
      fields=[
        (
          "id",
          models.BigAutoField(
            auto_created=True,
            primary_key=True,
            serialize=False,
            verbose_name="ID",
          ),
        ),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
        (
          "status",
          models.CharField(
            choices=[
              ("generating", "생성 중"),
              ("completed", "완료"),
              ("failed", "실패"),
            ],
            default="generating",
            max_length=15,
          ),
        ),
        ("error_message", models.TextField(blank=True, default="")),
        ("overall_score", models.IntegerField(null=True)),
        (
          "overall_grade",
          models.CharField(blank=True, default="", max_length=20),
        ),
        ("overall_comment", models.TextField(blank=True, default="")),
        ("category_scores", models.JSONField(default=list)),
        ("question_feedbacks", models.JSONField(default=list)),
        ("strengths", models.JSONField(default=list)),
        ("improvement_areas", models.JSONField(default=list)),
        ("input_tokens", models.IntegerField(default=0)),
        ("output_tokens", models.IntegerField(default=0)),
        ("total_tokens", models.IntegerField(default=0)),
        (
          "total_cost_usd",
          models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        (
          "session",
          models.OneToOneField(
            on_delete=django.db.models.deletion.CASCADE,
            related_name="report",
            to="interview.interviewsession",
          ),
        ),
      ],
      options={
        "verbose_name": "Analysis Report",
        "verbose_name_plural": "Analysis Reports",
        "db_table": "analysis_reports",
        "ordering": ["-created_at"],
        "get_latest_by": "created_at",
        "abstract": False,
        "indexes": [
          models.Index(fields=["-created_at"], name="analysis_re_created_d05995_idx"),
          models.Index(fields=["-updated_at"], name="analysis_re_updated_b0c4a7_idx"),
        ],
      },
      managers=[
        ("objects", common.models.base_model.BaseModelManager()),
      ],
    ),
  ]
