# Generated by Django 6.0.3 on 2026-04-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('interview', '0005_add_analysis_report'),
  ]

  operations = [
    migrations.AddField(
      model_name='interviewsession',
      name='question_sources',
      field=models.JSONField(blank=True, default=dict, help_text='질문별 source 매핑 {question_text: source}'),
    ),
  ]
