# Generated by Django 6.0.3 on 2026-04-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('interview', '0006_interviewsession_question_sources'),
  ]

  operations = [
    migrations.AlterField(
      model_name='analysisreport',
      name='status',
      field=models.CharField(
        choices=[('pending', '대기 중'), ('generating', '생성 중'), ('completed', '완료'), ('failed', '실패')],
        default='generating',
        max_length=15
      ),
    ),
  ]
