# Generated by Django 6.0.3 on 2026-04-08 18:06

from decimal import Decimal

import common.models.base_model
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

  initial = True

  dependencies = [
    ('contenttypes', '0002_remove_content_type_name'),
  ]

  operations = [
    migrations.CreateModel(
      name='TokenUsage',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('token_usable_id', models.CharField(max_length=40, verbose_name='관련 객체 PK')),
        (
          'operation',
          models.CharField(
            choices=[('completion', '텍스트 생성 (Chat Completion)'), ('embedding', '임베딩 생성')],
            max_length=20,
            verbose_name='LLM 연산 종류'
          )
        ),
        (
          'context',
          models.CharField(
            choices=[
              ('interview_question', '면접 초기 질문 생성'), ('interview_followup', '꼬리질문 생성'),
              ('interview_analysis', '면접 분석 리포트 생성'), ('resume_embed', '이력서 임베딩'), ('resume_analyze', '이력서 LLM 분석'),
              ('resume_search', '이력서 임베딩 검색'), ('other', '기타')
            ],
            default='other',
            max_length=30,
            verbose_name='사용 컨텍스트'
          )
        ),
        ('model_name', models.CharField(max_length=100, verbose_name='LLM 모델명')),
        ('input_tokens', models.PositiveIntegerField(default=0, verbose_name='입력 토큰')),
        ('output_tokens', models.PositiveIntegerField(default=0, verbose_name='출력 토큰')),
        ('total_tokens', models.PositiveIntegerField(default=0, verbose_name='전체 토큰')),
        (
          'cost_usd',
          models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=10, verbose_name='비용 (USD)')
        ),
        (
          'token_usable_type',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='관련 모델 타입'
          )
        ),
      ],
      options={
        'verbose_name': '토큰 사용 내역',
        'verbose_name_plural': '토큰 사용 내역 목록',
        'db_table': 'common_token_usages',
        'ordering': ['-created_at'],
        'get_latest_by': 'created_at',
        'abstract': False,
        'indexes': [
          models.Index(fields=['-created_at'], name='common_toke_created_ccb637_idx'),
          models.Index(fields=['-updated_at'], name='common_toke_updated_c28a81_idx')
        ],
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
  ]
