# Generated by Django 6.0.3 on 2026-04-02 11:03

import common.models.base_model
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

  initial = True

  dependencies = [
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name='SubscriptionPlanTicketPolicy',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        (
          'plan_type',
          models.CharField(choices=[('free', '무료'), ('pro', 'Pro')], max_length=20, unique=True, verbose_name='요금제')
        ),
        ('daily_ticket_amount', models.PositiveIntegerField(verbose_name='일일 지급 티켓 수')),
        ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
      ],
      options={
        'verbose_name': '구독 플랜 티켓 정책',
        'verbose_name_plural': '구독 플랜 티켓 정책 목록',
        'ordering': ['plan_type'],
        'get_latest_by': 'created_at',
        'abstract': False,
        'indexes': [
          models.Index(fields=['-created_at'], name='subscriptio_created_b8a529_idx'),
          models.Index(fields=['-updated_at'], name='subscriptio_updated_2d82ea_idx')
        ],
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
    migrations.CreateModel(
      name='Subscription',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        (
          'plan_type',
          models.CharField(choices=[('free', '무료'), ('pro', 'Pro')], default='free', max_length=20, verbose_name='요금제')
        ),
        ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='구독 시작일시')),
        (
          'expires_at',
          models.DateTimeField(blank=True, help_text='NULL이면 무기한 (무료 플랜)', null=True, verbose_name='구독 만료일시')
        ),
        (
          'cancelled_at',
          models.DateTimeField(
            blank=True, help_text='취소 의사를 표시한 일시. expires_at 전이면 여전히 ACTIVE.', null=True, verbose_name='구독 취소일시'
          )
        ),
        (
          'user',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='subscriptions',
            to=settings.AUTH_USER_MODEL,
            verbose_name='사용자'
          )
        ),
      ],
      options={
        'verbose_name': '구독',
        'verbose_name_plural': '구독 목록',
        'ordering': ['-started_at'],
        'get_latest_by': 'created_at',
        'abstract': False,
        'indexes': [
          models.Index(fields=['-created_at'], name='subscriptio_created_cd574f_idx'),
          models.Index(fields=['-updated_at'], name='subscriptio_updated_35f4a5_idx')
        ],
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
  ]
