# Generated by Django 6.0.3 on 2026-04-02 08:41

import common.models.base_model
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

  initial = True

  dependencies = [
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name='TicketLog',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        (
          'action_type',
          models.CharField(
            choices=[('grant', '발급'), ('use', '사용'), ('expire', '만료'), ('refund', '환불')],
            max_length=20,
            verbose_name='액션 타입'
          )
        ),
        ('amount', models.IntegerField(help_text='발급/환불은 양수, 사용/만료는 음수', verbose_name='변동 수량')),
        ('balance_after', models.PositiveIntegerField(verbose_name='변동 후 잔액')),
        (
          'reason',
          models.CharField(blank=True, help_text='티켓 발급/사용 사유 (예: 출석 보상, 면접 사용 등)', max_length=200, verbose_name='사유')
        ),
        (
          'metadata',
          models.JSONField(blank=True, default=dict, help_text='추가 정보 (예: 관련 객체 ID, 이벤트 정보 등)', verbose_name='메타데이터')
        ),
        (
          'user',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='ticket_logs',
            to=settings.AUTH_USER_MODEL,
            verbose_name='사용자'
          )
        ),
      ],
      options={
        'verbose_name': '티켓 이력',
        'verbose_name_plural': '티켓 이력 목록',
        'ordering': ['-created_at'],
        'get_latest_by': 'created_at',
        'abstract': False,
        'indexes': [
          models.Index(fields=['user', '-created_at'], name='tickets_tic_user_id_44faf6_idx'),
          models.Index(fields=['action_type', '-created_at'], name='tickets_tic_action__329bb8_idx')
        ],
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
    migrations.CreateModel(
      name='UserTicket',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        (
          'daily_count',
          models.PositiveIntegerField(default=0, help_text='구독 정책에 의해 매일 리셋되는 티켓', verbose_name='일일 티켓 수')
        ),
        (
          'purchased_count',
          models.PositiveIntegerField(default=0, help_text='구매/보상 등으로 획득한 영구 티켓', verbose_name='구매 티켓 수')
        ),
        (
          'user',
          models.OneToOneField(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='ticket',
            to=settings.AUTH_USER_MODEL,
            verbose_name='사용자'
          )
        ),
      ],
      options={
        'verbose_name': '사용자 티켓',
        'verbose_name_plural': '사용자 티켓 목록',
        'ordering': ['-created_at'],
        'get_latest_by': 'created_at',
        'abstract': False,
        'indexes': [
          models.Index(fields=['-created_at'], name='tickets_use_created_da1e39_idx'),
          models.Index(fields=['-updated_at'], name='tickets_use_updated_377e7c_idx')
        ],
        'constraints': [models.UniqueConstraint(fields=('user', ), name='unique_user_ticket')],
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
  ]
