apiVersion: v1
kind: Service
metadata:
  name: mefit-llm-gateway
  namespace: mefit-backend-production
  labels:
    app: mefit-production-llm-gateway
spec:
  selector:
    app: mefit-production-llm-gateway
  ports:
    - name: http
      port: 4000
      targetPort: 4000
  type: ClusterIP
