# Generated by Django 6.0.3 on 2026-04-08 18:06

import uuid

import common.models.base_model
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

  initial = True

  dependencies = [
    ('job_descriptions', '0002_userjobdescription'),
    ('resumes', '0001_initial'),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name='InterviewSession',
      fields=[
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        (
          'session_type',
          models.CharField(
            choices=[('followup', '꼬리질문형 면접'), ('full_process', '전체 프로세스 면접')], max_length=20, verbose_name='세션 유형'
          )
        ),
        (
          'session_status',
          models.CharField(
            choices=[('in_progress', '진행 중'), ('completed', '완료'), ('abandoned', '이탈')],
            default='in_progress',
            max_length=20,
            verbose_name='세션 상태'
          )
        ),
        (
          'difficulty_level',
          models.CharField(
            choices=[('friendly', '친근한 면접관'), ('normal', '일반 면접관'), ('pressure', '압박 면접관')],
            default='normal',
            max_length=20,
            verbose_name='난이도'
          )
        ),
        ('total_questions', models.PositiveIntegerField(default=0, verbose_name='총 질문 수')),
        ('total_followup_questions', models.PositiveIntegerField(default=0, verbose_name='총 꼬리질문 수')),
        (
          'resume',
          models.ForeignKey(
            blank=True,
            null=True,
            on_delete=django.db.models.deletion.SET_NULL,
            related_name='interview_sessions',
            to='resumes.resume',
            verbose_name='이력서'
          )
        ),
        (
          'user',
          models.ForeignKey(
            blank=True,
            null=True,
            on_delete=django.db.models.deletion.SET_NULL,
            related_name='interview_sessions',
            to=settings.AUTH_USER_MODEL,
            verbose_name='사용자'
          )
        ),
        (
          'user_job_description',
          models.ForeignKey(
            blank=True,
            null=True,
            on_delete=django.db.models.deletion.SET_NULL,
            related_name='interview_sessions',
            to='job_descriptions.userjobdescription',
            verbose_name='사용자 채용공고'
          )
        ),
      ],
      options={
        'verbose_name': '면접 세션',
        'verbose_name_plural': '면접 세션 목록',
        'db_table': 'interview_sessions',
        'abstract': False,
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
    migrations.CreateModel(
      name='AnalysisReport',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        (
          'analysis_report_status',
          models.CharField(
            choices=[('pending', '대기 중'), ('generating', '생성 중'), ('completed', '완료'), ('failed', '실패')],
            default='pending',
            max_length=15,
            verbose_name='리포트 상태'
          )
        ),
        ('error_message', models.TextField(blank=True, default='', verbose_name='에러 메시지')),
        ('overall_score', models.IntegerField(blank=True, null=True, verbose_name='종합 점수')),
        ('overall_grade', models.CharField(blank=True, default='', max_length=20, verbose_name='종합 등급')),
        ('overall_comment', models.TextField(blank=True, default='', verbose_name='종합 코멘트')),
        ('category_scores', models.JSONField(default=list, verbose_name='카테고리별 점수')),
        ('question_feedbacks', models.JSONField(default=list, verbose_name='질문별 피드백')),
        ('strengths', models.JSONField(default=list, verbose_name='강점')),
        ('improvement_areas', models.JSONField(default=list, verbose_name='개선 영역')),
        (
          'session',
          models.OneToOneField(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='analysis_report',
            to='interviews.interviewsession',
            verbose_name='면접 세션'
          )
        ),
      ],
      options={
        'verbose_name': '면접 분석 리포트',
        'verbose_name_plural': '면접 분석 리포트 목록',
        'db_table': 'analysis_reports',
        'ordering': ['-created_at'],
        'get_latest_by': 'created_at',
        'abstract': False,
        'indexes': [
          models.Index(fields=['-created_at'], name='analysis_re_created_d05995_idx'),
          models.Index(fields=['-updated_at'], name='analysis_re_updated_b0c4a7_idx')
        ],
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
    migrations.CreateModel(
      name='InterviewTurn',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        (
          'turn_type',
          models.CharField(choices=[('initial', '초기 질문'), ('followup', '꼬리질문')], max_length=10, verbose_name='턴 유형')
        ),
        (
          'question_source',
          models.CharField(
            choices=[('resume', '이력서'), ('job_description', '채용공고'), ('unknown', '미분류')],
            default='unknown',
            max_length=20,
            verbose_name='질문 출처'
          )
        ),
        ('question', models.TextField(verbose_name='질문')),
        ('answer', models.TextField(blank=True, default='', verbose_name='답변')),
        ('turn_number', models.PositiveIntegerField(default=1, verbose_name='턴 번호')),
        (
          'session',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='turns',
            to='interviews.interviewsession',
            verbose_name='면접 세션'
          )
        ),
      ],
      options={
        'verbose_name': '면접 턴',
        'verbose_name_plural': '면접 턴 목록',
        'db_table': 'interview_turns',
        'ordering': ['created_at'],
        'get_latest_by': 'created_at',
        'abstract': False,
        'indexes': [
          models.Index(fields=['-created_at'], name='interview_t_created_a19720_idx'),
          models.Index(fields=['-updated_at'], name='interview_t_updated_30aed1_idx')
        ],
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
  ]
