# Generated by Django 6.0.3 on 2026-04-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('interviews', '0001_initial'),
  ]

  operations = [
    migrations.AddField(
      model_name='interviewturn',
      name='followup_order',
      field=models.PositiveIntegerField(
        blank=True, help_text='follow-up인 경우에만 값이 있음 (1부터 순차)', null=True, verbose_name='꼬리질문 순번'
      ),
    ),
    migrations.AlterField(
      model_name='interviewturn',
      name='turn_number',
      field=models.PositiveIntegerField(default=1, help_text='앵커는 1부터 순차, follow-up은 앵커와 동일', verbose_name='턴 번호'),
    ),
  ]
