# Generated by Django 6.0.3 on 2026-04-17 19:07

import uuid

import common.models.base_model
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('interviews', '0002_interviewturn_followup_order_and_more'),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name='InterviewRecording',
      fields=[
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        (
          'media_type',
          models.CharField(choices=[('video', 'Video'), ('audio', 'Audio')], max_length=10, verbose_name='미디어 유형')
        ),
        (
          'status',
          models.CharField(
            choices=[
              ('initiated', 'Initiated'), ('uploading', 'Uploading'), ('completed', 'Completed'),
              ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')
            ],
            default='initiated',
            max_length=20,
            verbose_name='상태'
          )
        ),
        ('s3_bucket', models.CharField(max_length=100, verbose_name='S3 버킷')),
        ('s3_key', models.CharField(max_length=500, verbose_name='S3 키')),
        ('upload_id', models.CharField(blank=True, default='', max_length=200, verbose_name='업로드 ID')),
        ('start_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='녹화 시작 시각')),
        ('end_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='녹화 종료 시각')),
        ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='녹화 길이 (ms)')),
        ('scaled_video_key', models.CharField(blank=True, default='', max_length=500, verbose_name='스케일 영상 S3 키')),
        ('frame_prefix', models.CharField(blank=True, default='', max_length=500, verbose_name='프레임 S3 접두사')),
        ('audio_key', models.CharField(blank=True, default='', max_length=500, verbose_name='음성 S3 키')),
        ('scaled_audio_key', models.CharField(blank=True, default='', max_length=500, verbose_name='스케일 음성 S3 키')),
        (
          'interview_session',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='recordings',
            to='interviews.interviewsession',
            verbose_name='면접 세션'
          )
        ),
        (
          'interview_turn',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='recordings',
            to='interviews.interviewturn',
            verbose_name='면접 턴'
          )
        ),
        (
          'user',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='interview_recordings',
            to=settings.AUTH_USER_MODEL,
            verbose_name='사용자'
          )
        ),
      ],
      options={
        'verbose_name': '면접 녹화',
        'verbose_name_plural': '면접 녹화 목록',
        'db_table': 'interview_recordings',
        'ordering': ['created_at'],
        'abstract': False,
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
  ]
