# Generated by Django 6.0.3 on 2026-04-17 19:42

import uuid

import common.models.base_model
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('interviews', '0003_interviewrecording'),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name='InterviewBehaviorAnalysis',
      fields=[
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        (
          'status',
          models.CharField(
            choices=[
              ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')
            ],
            default='pending',
            max_length=20,
            verbose_name='상태'
          )
        ),
        ('expression_data', models.JSONField(blank=True, default=dict, verbose_name='표정 분석 데이터')),
        ('speech_data', models.JSONField(blank=True, default=dict, verbose_name='음성 분석 데이터')),
        (
          'interview_recording',
          models.ForeignKey(
            blank=True,
            null=True,
            on_delete=django.db.models.deletion.CASCADE,
            related_name='behavior_analyses',
            to='interviews.interviewrecording',
            verbose_name='면접 녹화'
          )
        ),
        (
          'interview_session',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='behavior_analyses',
            to='interviews.interviewsession',
            verbose_name='면접 세션'
          )
        ),
        (
          'interview_turn',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='behavior_analyses',
            to='interviews.interviewturn',
            verbose_name='면접 턴'
          )
        ),
        (
          'user',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='behavior_analyses',
            to=settings.AUTH_USER_MODEL,
            verbose_name='사용자'
          )
        ),
      ],
      options={
        'verbose_name': '면접 행동 분석',
        'verbose_name_plural': '면접 행동 분석 목록',
        'db_table': 'interview_behavior_analyses',
        'abstract': False,
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
  ]
