# Generated by Django 6.0.3 on 2026-04-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('interviews', '0004_interviewbehavioranalysis'),
  ]

  operations = [
    migrations.AddField(
      model_name='interviewturn',
      name='speech_segments',
      field=models.JSONField(blank=True, default=list, verbose_name='발화 세그먼트'),
    ),
    migrations.AlterField(
      model_name='interviewrecording',
      name='status',
      field=models.CharField(
        choices=[
          ('initiated', 'Initiated'), ('uploading', 'Uploading'), ('completed', 'Completed'),
          ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('abandoned', 'Abandoned')
        ],
        default='initiated',
        max_length=20,
        verbose_name='상태'
      ),
    ),
  ]
