# Generated by Django 6.0.3 on 2026-04-26 09:13

import common.models.base_model
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('interviews', '0005_add_speech_segments_to_turn'),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name='UserPracticeTimeStatistics',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('total_practice_time_seconds', models.PositiveBigIntegerField(default=0, verbose_name='총 연습 시간 (초)')),
        ('total_practice_sessions_count', models.PositiveIntegerField(default=0, verbose_name='집계된 녹화 수')),
        ('last_calculated_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 재계산 시각')),
        (
          'user',
          models.OneToOneField(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='practice_time_statistic',
            to=settings.AUTH_USER_MODEL,
            verbose_name='사용자'
          )
        ),
      ],
      options={
        'verbose_name': '사용자 연습시간 통계',
        'verbose_name_plural': '사용자 연습시간 통계 목록',
        'db_table': 'user_practice_time_statistics',
        'ordering': ['-created_at'],
        'get_latest_by': 'created_at',
        'abstract': False,
        'indexes': [
          models.Index(fields=['-created_at'], name='user_practi_created_ca2ed7_idx'),
          models.Index(fields=['-updated_at'], name='user_practi_updated_afff03_idx')
        ],
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
  ]
