# Generated by Django 6.0.3 on 2026-04-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('interviews', '0006_userpracticetimestatistics'),
  ]

  operations = [
    migrations.AddField(
      model_name='interviewsession',
      name='last_heartbeat_at',
      field=models.DateTimeField(blank=True, null=True, verbose_name='최종 하트비트 수신 시각'),
    ),
    migrations.AddField(
      model_name='interviewsession',
      name='owner_token_hash',
      field=models.CharField(blank=True, default='', max_length=128, verbose_name='소유 토큰 해시'),
    ),
    migrations.AddField(
      model_name='interviewsession',
      name='owner_version',
      field=models.PositiveIntegerField(default=0, verbose_name='소유권 버전'),
    ),
    migrations.AddField(
      model_name='interviewsession',
      name='pause_count',
      field=models.PositiveIntegerField(default=0, verbose_name='일시정지 횟수'),
    ),
    migrations.AddField(
      model_name='interviewsession',
      name='pause_reason',
      field=models.CharField(blank=True, default='', max_length=20, verbose_name='일시정지 사유'),
    ),
    migrations.AddField(
      model_name='interviewsession',
      name='paused_at',
      field=models.DateTimeField(blank=True, null=True, verbose_name='일시정지 시각'),
    ),
    migrations.AddField(
      model_name='interviewsession',
      name='total_paused_duration_ms',
      field=models.BigIntegerField(default=0, verbose_name='누적 일시정지 시간(ms)'),
    ),
    migrations.AlterField(
      model_name='interviewsession',
      name='interview_session_status',
      field=models.CharField(
        choices=[('in_progress', '진행 중'), ('paused', '일시정지'), ('completed', '완료')],
        default='in_progress',
        max_length=20,
        verbose_name='세션 상태'
      ),
    ),
  ]
