# Generated by Django 6.0.3 on 2026-04-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('interviews', '0006_userpracticetimestatistics'),
  ]

  operations = [
    migrations.AddField(
      model_name='interviewsession',
      name='last_heartbeat_at',
      field=models.DateTimeField(blank=True, null=True, verbose_name='최종 하트비트 수신 시각'),
    ),
    migrations.AddField(
      model_name='interviewsession',
      name='owner_token_hash',
      field=models.CharField(blank=True, default='', max_length=128, verbose_name='소유 토큰 해시'),
    ),
    migrations.AddField(
      model_name='interviewsession',
      name='owner_version',
      field=models.PositiveIntegerField(default=0, verbose_name='소유권 버전'),
    ),
    migrations.AddField(
      model_name='interviewsession',
      name='pause_count',
      field=models.PositiveIntegerField(default=0, verbose_name='일시정지 횟수'),
    ),
    migrations.AddField(
      model_name='interviewsession',
      name='pause_reason',
      field=models.CharField(blank=True, default='', max_length=20, verbose_name='일시정지 사유'),
    ),
    migrations.AddField(
      model_name='interviewsession',
      name='paused_at',
      field=models.DateTimeField(blank=True, null=True, verbose_name='일시정지 시각'),
    ),
    migrations.AddField(
      model_name='interviewsession',
      name='stt_mode',
      field=models.CharField(
        choices=[('browser', 'Browser'), ('backend', 'Backend')],
        default='browser',
        max_length=20,
        verbose_name='STT 모드'
      ),
    ),
    migrations.AddField(
      model_name='interviewsession',
      name='total_paused_duration_ms',
      field=models.BigIntegerField(default=0, verbose_name='누적 일시정지 시간(ms)'),
    ),
    migrations.AddField(
      model_name='interviewturn',
      name='transcript_error_code',
      field=models.CharField(blank=True, default='', max_length=50, verbose_name='STT 에러 코드'),
    ),
    migrations.AddField(
      model_name='interviewturn',
      name='transcript_source',
      field=models.CharField(
        choices=[('browser_stt', 'Browser Stt'), ('backend_stt', 'Backend Stt'), ('none', 'None')],
        default='browser_stt',
        max_length=20,
        verbose_name='STT 출처'
      ),
    ),
    migrations.AddField(
      model_name='interviewturn',
      name='transcript_status',
      field=models.CharField(
        blank=True,
        choices=[
          ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')
        ],
        default=None,
        help_text='None=브라우저 STT 정상 / pending=백엔드 STT 대기 / processing/completed/failed',
        max_length=20,
        null=True,
        verbose_name='STT 상태'
      ),
    ),
    migrations.AlterField(
      model_name='interviewsession',
      name='interview_session_status',
      field=models.CharField(
        choices=[('in_progress', '진행 중'), ('paused', '일시정지'), ('completed', '완료')],
        default='in_progress',
        max_length=20,
        verbose_name='세션 상태'
      ),
    ),
  ]
