# Generated by Django 6.0.3 on 2026-04-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('interviews', '0007_interviewsession_last_heartbeat_at_and_more'),
  ]

  operations = [
    migrations.AddField(
      model_name='interviewturn',
      name='transcript_text',
      field=models.TextField(
        blank=True,
        default='',
        help_text='audio 의 객관적 STT 결과 (analysis-stt worker 가 채움). user 의 answer 와 별개.',
        verbose_name='STT 텍스트'
      ),
    ),
  ]
