# Generated by Django 6.0.3 on 2026-05-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('interviews', '0009_interviewrecording_face_analysis_result_and_more'),
  ]

  operations = [
    migrations.AddField(
      model_name='interviewturn',
      name='gaze_away_count',
      field=models.PositiveIntegerField(
        default=0, help_text='녹화 중 사용자의 시선이 정면에서 이탈한 누적 횟수 (false→true 전이 단위).', verbose_name='시선 이탈 횟수'
      ),
    ),
    migrations.AddField(
      model_name='interviewturn',
      name='head_away_count',
      field=models.PositiveIntegerField(
        default=0, help_text='녹화 중 사용자의 고개가 정면에서 이탈한 누적 횟수 (false→true 전이 단위).', verbose_name='고개 이탈 횟수'
      ),
    ),
    migrations.AddField(
      model_name='interviewturn',
      name='pillar_word_counts',
      field=models.JSONField(
        blank=True,
        default=dict,
        help_text='발화 중 사용된 필러 단어별 사용 횟수. 예: {"음": 5, "어": 3, "근데": 1}',
        verbose_name='필러 단어 사용 빈도'
      ),
    ),
    migrations.AddField(
      model_name='interviewturn',
      name='speech_rate_sps',
      field=models.FloatField(
        blank=True, help_text='총 음절 수 / 총 발화 시간(초). 측정 불가 시 null.', null=True, verbose_name='발화 속도 (음절/초)'
      ),
    ),
  ]
