# Generated by Django 6.0.3 on 2026-04-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('interviews', '0009_add_active_session_unique_index'),
  ]

  operations = [
    migrations.AddField(
      model_name='interviewsession',
      name='stt_mode',
      field=models.CharField(
        choices=[('browser', 'Browser'), ('backend', 'Backend')],
        default='browser',
        max_length=20,
        verbose_name='STT 모드'
      ),
    ),
    migrations.AddField(
      model_name='interviewturn',
      name='transcript_error_code',
      field=models.CharField(blank=True, default='', max_length=50, verbose_name='STT 에러 코드'),
    ),
    migrations.AddField(
      model_name='interviewturn',
      name='transcript_source',
      field=models.CharField(
        choices=[('browser_stt', 'Browser Stt'), ('backend_stt', 'Backend Stt'), ('none', 'None')],
        default='browser_stt',
        max_length=20,
        verbose_name='STT 출처'
      ),
    ),
    migrations.AddField(
      model_name='interviewturn',
      name='transcript_status',
      field=models.CharField(
        blank=True,
        choices=[
          ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')
        ],
        default=None,
        help_text='None=브라우저 STT 정상 / pending=백엔드 STT 대기 / processing/completed/failed',
        max_length=20,
        null=True,
        verbose_name='STT 상태'
      ),
    ),
  ]
