# Generated by Django 6.0.3 on 2026-05-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('interviews', '0010_interviewturn_gaze_away_count_and_more'),
  ]

  operations = [
    migrations.AddField(
      model_name='interviewanalysisreport',
      name='audio_analysis_comment',
      field=models.TextField(blank=True, default='', verbose_name='음성 분석 코멘트'),
    ),
    migrations.AddField(
      model_name='interviewanalysisreport',
      name='audio_analysis_result',
      field=models.JSONField(blank=True, default=dict, verbose_name='음성 분석 결과'),
    ),
    migrations.AddField(
      model_name='interviewanalysisreport',
      name='audio_score',
      field=models.IntegerField(blank=True, null=True, verbose_name='음성 점수'),
    ),
    migrations.AddField(
      model_name='interviewanalysisreport',
      name='content_score',
      field=models.IntegerField(blank=True, null=True, verbose_name='텍스트 점수'),
    ),
    migrations.AddField(
      model_name='interviewanalysisreport',
      name='video_analysis_comment',
      field=models.TextField(blank=True, default='', verbose_name='영상 분석 코멘트'),
    ),
    migrations.AddField(
      model_name='interviewanalysisreport',
      name='video_analysis_result',
      field=models.JSONField(blank=True, default=dict, verbose_name='영상 분석 결과'),
    ),
    migrations.AddField(
      model_name='interviewanalysisreport',
      name='video_score',
      field=models.IntegerField(blank=True, null=True, verbose_name='영상 점수'),
    ),
  ]
