# Generated by Django 6.0.3 on 2026-04-01 11:01

import common.models.base_model
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

  initial = True

  dependencies = [
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name='DailyInterviewRewardPolicy',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('interview_order', models.PositiveSmallIntegerField(unique=True, verbose_name='인터뷰 순서 (1~5)')),
        ('ticket_reward', models.PositiveIntegerField(verbose_name='지급 티켓 수')),
        ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
      ],
      options={
        'verbose_name': '일일 인터뷰 보상 정책',
        'verbose_name_plural': '일일 인터뷰 보상 정책 목록',
        'ordering': ['interview_order'],
        'get_latest_by': 'created_at',
        'abstract': False,
        'indexes': [
          models.Index(fields=['-created_at'], name='streaks_dai_created_924431_idx'),
          models.Index(fields=['-updated_at'], name='streaks_dai_updated_93e244_idx')
        ],
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
    migrations.CreateModel(
      name='StreakLog',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('date', models.DateField(verbose_name='참여 날짜')),
        ('interview_results_count', models.PositiveIntegerField(default=0, verbose_name='해당 날 면접 참여 횟수')),
        (
          'user',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='streak_logs',
            to=settings.AUTH_USER_MODEL,
            verbose_name='사용자'
          )
        ),
      ],
      options={
        'verbose_name': '스트릭 로그',
        'verbose_name_plural': '스트릭 로그 목록',
        'ordering': ['-created_at'],
        'get_latest_by': 'created_at',
        'abstract': False,
        'indexes': [
          models.Index(fields=['-created_at'], name='streaks_str_created_2d0fe7_idx'),
          models.Index(fields=['-updated_at'], name='streaks_str_updated_76e75a_idx')
        ],
        'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_streak_log_user_date')],
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
    migrations.CreateModel(
      name='StreakStatistics',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('current_streak', models.PositiveIntegerField(default=0, verbose_name='현재 연속 일수')),
        ('longest_streak', models.PositiveIntegerField(default=0, verbose_name='역대 최장 연속 일수')),
        ('last_participated_date', models.DateField(blank=True, null=True, verbose_name='마지막 참여 날짜')),
        (
          'user',
          models.OneToOneField(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='streak_statistics',
            to=settings.AUTH_USER_MODEL,
            verbose_name='사용자'
          )
        ),
      ],
      options={
        'verbose_name': '스트릭 통계',
        'verbose_name_plural': '스트릭 통계 목록',
        'ordering': ['-created_at'],
        'get_latest_by': 'created_at',
        'abstract': False,
        'indexes': [
          models.Index(fields=['-created_at'], name='streaks_str_created_0fc2a7_idx'),
          models.Index(fields=['-updated_at'], name='streaks_str_updated_a8a3e6_idx')
        ],
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
  ]
