# Generated by Django 6.0.3 on 2026-04-02 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('streaks', '0001_initial'),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.AlterField(
      model_name='streakstatistics',
      name='user',
      field=models.OneToOneField(
        on_delete=django.db.models.deletion.CASCADE,
        related_name='streak_statistic',
        to=settings.AUTH_USER_MODEL,
        verbose_name='사용자'
      ),
    ),
  ]
