# Generated by Django 6.0.3 on 2026-04-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('streaks', '0002_alter_streakstatistics_user'),
  ]

  operations = [
    migrations.AddField(
      model_name='streakstatistics',
      name='total_days',
      field=models.PositiveIntegerField(default=0, verbose_name='총 참여일'),
    ),
  ]
