"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from .components.admin import *
from .components.auth import *
from .components.celery import *
from .components.celery_beat import *
from .components.common import *
from .components.database import *
from .components.file import *
from .components.i18n import *
from .components.installed_app import *
from .components.middleware import *
from .components.rest_framework import *
from .components.template import *

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")

ROOT_URLCONF = 'config.urls'
