"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from corsheaders.defaults import default_headers

from .components.admin import *
from .components.auth import *
from .components.cache import *
from .components.celery import *
from .components.celery_beat import *
from .components.celery_sqs import *
from .components.channel_layer import *
from .components.common import *
from .components.database import *
from .components.i18n import *
from .components.installed_app import *
from .components.logging import *
from .components.middleware import *
from .components.rest_framework import *
from .components.s3 import *
from .components.slack import *
from .components.template import *
from .components.ticket_policy import *

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")

OPENAI_API_KEY = env.str("OPENAI_API_KEY", default="")
OPENAI_MODEL = env.str("OPENAI_MODEL", default="gpt-4o-mini")
OPENAI_EMBEDDING_MODEL = env.str("OPENAI_EMBEDDING_MODEL", default="text-embedding-3-small")
# LLM Gateway (LiteLLM) base URL.
# - 비어 있으면 OpenAI 직통 (로컬 개발 기본값)
# - 설정 시 게이트웨이 경유 (예: 운영 K3s = "http://mefit-llm-gateway:4000/v1",
#   로컬 docker-compose = "http://localhost:4000/v1")
OPENAI_BASE_URL = env.str("OPENAI_BASE_URL", default="")

ROOT_URLCONF = "config.urls"

CORS_ALLOW_HEADERS = (
  *default_headers,
  "x-session-owner-token",
  "x-session-owner-version",
)
