# Generated by Django 6.0.3 on 2026-03-23 09:57

import common.models.base_model_with_soft_delete
import django.db.models.deletion
import users.managers.user_manager
import users.models.email_verification_code
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

  initial = True

  dependencies = [
    ('auth', '0012_alter_user_first_name_max_length'),
  ]

  operations = [
    migrations.CreateModel(
      name='User',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('password', models.CharField(max_length=128, verbose_name='password')),
        ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
        (
          'is_superuser',
          models.BooleanField(
            default=False,
            help_text='Designates that this user has all permissions without explicitly assigning them.',
            verbose_name='superuser status'
          )
        ),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('deleted_at', models.DateTimeField(blank=True, null=True)),
        ('name', models.CharField(blank=True, default='', max_length=50)),
        ('email', models.EmailField(max_length=320, unique=True)),
        ('email_confirmed_at', models.DateTimeField(blank=True, null=True)),
        ('profile_completed_at', models.DateTimeField(blank=True, null=True)),
        ('is_staff', models.BooleanField(default=False)),
        ('is_active', models.BooleanField(default=True)),
        (
          'groups',
          models.ManyToManyField(
            blank=True,
            help_text=
            'The groups this user belongs to. A user will get all permissions granted to each of their groups.',
            related_name='user_set',
            related_query_name='user',
            to='auth.group',
            verbose_name='groups'
          )
        ),
        (
          'user_permissions',
          models.ManyToManyField(
            blank=True,
            help_text='Specific permissions for this user.',
            related_name='user_set',
            related_query_name='user',
            to='auth.permission',
            verbose_name='user permissions'
          )
        ),
      ],
      options={
        'verbose_name': 'User',
        'verbose_name_plural': 'Users',
        'db_table': 'users',
      },
      managers=[
        ('objects', users.managers.user_manager.UserManager()),
        ('all_objects', common.models.base_model_with_soft_delete.AllObjectsManager()),
      ],
    ),
    migrations.CreateModel(
      name='EmailVerificationCode',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('code', models.CharField(max_length=6)),
        ('expires_at', models.DateTimeField()),
        ('used_at', models.DateTimeField(blank=True, null=True)),
        (
          'user',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='email_verification_codes',
            to=settings.AUTH_USER_MODEL
          )
        ),
      ],
      options={
        'db_table': 'email_verification_codes',
        'indexes': [
          models.Index(fields=['user', 'used_at'], name='email_verif_user_id_15e41f_idx'),
          models.Index(fields=['code', 'used_at'], name='email_verif_code_2dd4c7_idx')
        ],
      },
      managers=[
        ('objects', users.models.email_verification_code.EmailVerificationCodeManager()),
      ],
    ),
  ]
