# Generated by Django 6.0.3 on 2026-04-21 11:02

import uuid

import django.db.models.deletion
import users.models.password_reset_token
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('users', '0001_initial'),
  ]

  operations = [
    migrations.CreateModel(
      name='PasswordResetToken',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
        ('expires_at', models.DateTimeField()),
        ('used_at', models.DateTimeField(blank=True, null=True)),
        (
          'user',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='password_reset_tokens',
            to=settings.AUTH_USER_MODEL,
            verbose_name='사용자'
          )
        ),
      ],
      options={
        'verbose_name': '비밀번호 재설정 토큰',
        'verbose_name_plural': '비밀번호 재설정 토큰 목록',
        'db_table': 'password_reset_tokens',
        'indexes': [
          models.Index(fields=['user', 'used_at'], name='password_re_user_id_9530b9_idx'),
          models.Index(fields=['token', 'used_at'], name='password_re_token_a0ec16_idx')
        ],
      },
      managers=[
        ('objects', users.models.password_reset_token.PasswordResetTokenManager()),
      ],
    ),
  ]
